### ISSUE TITLE
Since your last update get errors

### ISSUE THREAD

**Issue by jgerits** [Johannestegner/docker-youtrack#1]
Since your last upgrade to this docker i get some errors:
[YouTrack Error] Failed to start JetBrains YouTrack 2017.3 due to unexpected exception: File created by ConfigurationWizard is not accessible

**Comment by Johannestegner** [comment]
Could you possibly paste a short reproducible example of how you run the container?

**Comment by jgerits** [comment]
I have managed to solve the issue. For some reason one file was not accessable anymore. I edited it with chmod and it works now.

**Comment by Johannestegner** [comment]
Happy to see you got it fix. I'll see over the issue though and see if i can reproduce and fix it.
Thanks for the report!
